with-expecter: true
dir: "mocks/{{.InterfaceDirRelative}}"
filename: "{{.InterfaceName | lower}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
    github.com/rlebel12/gosesh:
        config:
            all: True
            recursive: True