version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: gosesh-postgres
    restart: unless-stopped
    ports:
      - "16001:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres_docker_entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=gosesh,atlas
volumes:
  postgres:
    driver: local
