// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package providers

import (
	"github.com/rlebel12/gosesh"
	"golang.org/x/oauth2"
	"net/http"
	"sync"
)

// Ensure, that GosesherMock does implement Gosesher.
// If this is not the case, regenerate this file with moq.
var _ Gosesher = &GosesherMock{}

// GosesherMock is a mock implementation of Gosesher.
//
//	func TestSomethingThatUsesGosesher(t *testing.T) {
//
//		// make and configure a mocked Gosesher
//		mockedGosesher := &GosesherMock{
//			HostFunc: func() string {
//				panic("mock out the Host method")
//			},
//			OAuth2BeginFunc: func(cfg *oauth2.Config) http.HandlerFunc {
//				panic("mock out the OAuth2Begin method")
//			},
//			OAuth2CallbackFunc: func(user gosesh.OAuth2User, cfg *oauth2.Config, handler gosesh.HandlerDone) http.HandlerFunc {
//				panic("mock out the OAuth2Callback method")
//			},
//			SchemeFunc: func() string {
//				panic("mock out the Scheme method")
//			},
//		}
//
//		// use mockedGosesher in code that requires Gosesher
//		// and then make assertions.
//
//	}
type GosesherMock struct {
	// HostFunc mocks the Host method.
	HostFunc func() string

	// OAuth2BeginFunc mocks the OAuth2Begin method.
	OAuth2BeginFunc func(cfg *oauth2.Config) http.HandlerFunc

	// OAuth2CallbackFunc mocks the OAuth2Callback method.
	OAuth2CallbackFunc func(user gosesh.OAuth2User, cfg *oauth2.Config, handler gosesh.HandlerDone) http.HandlerFunc

	// SchemeFunc mocks the Scheme method.
	SchemeFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Host holds details about calls to the Host method.
		Host []struct {
		}
		// OAuth2Begin holds details about calls to the OAuth2Begin method.
		OAuth2Begin []struct {
			// Cfg is the cfg argument value.
			Cfg *oauth2.Config
		}
		// OAuth2Callback holds details about calls to the OAuth2Callback method.
		OAuth2Callback []struct {
			// User is the user argument value.
			User gosesh.OAuth2User
			// Cfg is the cfg argument value.
			Cfg *oauth2.Config
			// Handler is the handler argument value.
			Handler gosesh.HandlerDone
		}
		// Scheme holds details about calls to the Scheme method.
		Scheme []struct {
		}
	}
	lockHost           sync.RWMutex
	lockOAuth2Begin    sync.RWMutex
	lockOAuth2Callback sync.RWMutex
	lockScheme         sync.RWMutex
}

// Host calls HostFunc.
func (mock *GosesherMock) Host() string {
	if mock.HostFunc == nil {
		panic("GosesherMock.HostFunc: method is nil but Gosesher.Host was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHost.Lock()
	mock.calls.Host = append(mock.calls.Host, callInfo)
	mock.lockHost.Unlock()
	return mock.HostFunc()
}

// HostCalls gets all the calls that were made to Host.
// Check the length with:
//
//	len(mockedGosesher.HostCalls())
func (mock *GosesherMock) HostCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHost.RLock()
	calls = mock.calls.Host
	mock.lockHost.RUnlock()
	return calls
}

// ResetHostCalls reset all the calls that were made to Host.
func (mock *GosesherMock) ResetHostCalls() {
	mock.lockHost.Lock()
	mock.calls.Host = nil
	mock.lockHost.Unlock()
}

// OAuth2Begin calls OAuth2BeginFunc.
func (mock *GosesherMock) OAuth2Begin(cfg *oauth2.Config) http.HandlerFunc {
	if mock.OAuth2BeginFunc == nil {
		panic("GosesherMock.OAuth2BeginFunc: method is nil but Gosesher.OAuth2Begin was just called")
	}
	callInfo := struct {
		Cfg *oauth2.Config
	}{
		Cfg: cfg,
	}
	mock.lockOAuth2Begin.Lock()
	mock.calls.OAuth2Begin = append(mock.calls.OAuth2Begin, callInfo)
	mock.lockOAuth2Begin.Unlock()
	return mock.OAuth2BeginFunc(cfg)
}

// OAuth2BeginCalls gets all the calls that were made to OAuth2Begin.
// Check the length with:
//
//	len(mockedGosesher.OAuth2BeginCalls())
func (mock *GosesherMock) OAuth2BeginCalls() []struct {
	Cfg *oauth2.Config
} {
	var calls []struct {
		Cfg *oauth2.Config
	}
	mock.lockOAuth2Begin.RLock()
	calls = mock.calls.OAuth2Begin
	mock.lockOAuth2Begin.RUnlock()
	return calls
}

// ResetOAuth2BeginCalls reset all the calls that were made to OAuth2Begin.
func (mock *GosesherMock) ResetOAuth2BeginCalls() {
	mock.lockOAuth2Begin.Lock()
	mock.calls.OAuth2Begin = nil
	mock.lockOAuth2Begin.Unlock()
}

// OAuth2Callback calls OAuth2CallbackFunc.
func (mock *GosesherMock) OAuth2Callback(user gosesh.OAuth2User, cfg *oauth2.Config, handler gosesh.HandlerDone) http.HandlerFunc {
	if mock.OAuth2CallbackFunc == nil {
		panic("GosesherMock.OAuth2CallbackFunc: method is nil but Gosesher.OAuth2Callback was just called")
	}
	callInfo := struct {
		User    gosesh.OAuth2User
		Cfg     *oauth2.Config
		Handler gosesh.HandlerDone
	}{
		User:    user,
		Cfg:     cfg,
		Handler: handler,
	}
	mock.lockOAuth2Callback.Lock()
	mock.calls.OAuth2Callback = append(mock.calls.OAuth2Callback, callInfo)
	mock.lockOAuth2Callback.Unlock()
	return mock.OAuth2CallbackFunc(user, cfg, handler)
}

// OAuth2CallbackCalls gets all the calls that were made to OAuth2Callback.
// Check the length with:
//
//	len(mockedGosesher.OAuth2CallbackCalls())
func (mock *GosesherMock) OAuth2CallbackCalls() []struct {
	User    gosesh.OAuth2User
	Cfg     *oauth2.Config
	Handler gosesh.HandlerDone
} {
	var calls []struct {
		User    gosesh.OAuth2User
		Cfg     *oauth2.Config
		Handler gosesh.HandlerDone
	}
	mock.lockOAuth2Callback.RLock()
	calls = mock.calls.OAuth2Callback
	mock.lockOAuth2Callback.RUnlock()
	return calls
}

// ResetOAuth2CallbackCalls reset all the calls that were made to OAuth2Callback.
func (mock *GosesherMock) ResetOAuth2CallbackCalls() {
	mock.lockOAuth2Callback.Lock()
	mock.calls.OAuth2Callback = nil
	mock.lockOAuth2Callback.Unlock()
}

// Scheme calls SchemeFunc.
func (mock *GosesherMock) Scheme() string {
	if mock.SchemeFunc == nil {
		panic("GosesherMock.SchemeFunc: method is nil but Gosesher.Scheme was just called")
	}
	callInfo := struct {
	}{}
	mock.lockScheme.Lock()
	mock.calls.Scheme = append(mock.calls.Scheme, callInfo)
	mock.lockScheme.Unlock()
	return mock.SchemeFunc()
}

// SchemeCalls gets all the calls that were made to Scheme.
// Check the length with:
//
//	len(mockedGosesher.SchemeCalls())
func (mock *GosesherMock) SchemeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockScheme.RLock()
	calls = mock.calls.Scheme
	mock.lockScheme.RUnlock()
	return calls
}

// ResetSchemeCalls reset all the calls that were made to Scheme.
func (mock *GosesherMock) ResetSchemeCalls() {
	mock.lockScheme.Lock()
	mock.calls.Scheme = nil
	mock.lockScheme.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *GosesherMock) ResetCalls() {
	mock.lockHost.Lock()
	mock.calls.Host = nil
	mock.lockHost.Unlock()

	mock.lockOAuth2Begin.Lock()
	mock.calls.OAuth2Begin = nil
	mock.lockOAuth2Begin.Unlock()

	mock.lockOAuth2Callback.Lock()
	mock.calls.OAuth2Callback = nil
	mock.lockOAuth2Callback.Unlock()

	mock.lockScheme.Lock()
	mock.calls.Scheme = nil
	mock.lockScheme.Unlock()
}
