// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_gosesh

import mock "github.com/stretchr/testify/mock"

// Identifier is an autogenerated mock type for the Identifier type
type Identifier struct {
	mock.Mock
}

type Identifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Identifier) EXPECT() *Identifier_Expecter {
	return &Identifier_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with given fields:
func (_m *Identifier) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Identifier_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type Identifier_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *Identifier_Expecter) ID() *Identifier_ID_Call {
	return &Identifier_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Identifier_ID_Call) Run(run func()) *Identifier_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identifier_ID_Call) Return(_a0 string) *Identifier_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Identifier_ID_Call) RunAndReturn(run func() string) *Identifier_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentifier creates a new instance of Identifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Identifier {
	mock := &Identifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
