// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_gosesh

import (
	gosesh "github.com/rlebel12/gosesh"
	mock "github.com/stretchr/testify/mock"
)

// NewOpts is an autogenerated mock type for the NewOpts type
type NewOpts struct {
	mock.Mock
}

type NewOpts_Expecter struct {
	mock *mock.Mock
}

func (_m *NewOpts) EXPECT() *NewOpts_Expecter {
	return &NewOpts_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *NewOpts) Execute(_a0 *gosesh.Gosesh) {
	_m.Called(_a0)
}

// NewOpts_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type NewOpts_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *gosesh.Gosesh
func (_e *NewOpts_Expecter) Execute(_a0 interface{}) *NewOpts_Execute_Call {
	return &NewOpts_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *NewOpts_Execute_Call) Run(run func(_a0 *gosesh.Gosesh)) *NewOpts_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gosesh.Gosesh))
	})
	return _c
}

func (_c *NewOpts_Execute_Call) Return() *NewOpts_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *NewOpts_Execute_Call) RunAndReturn(run func(*gosesh.Gosesh)) *NewOpts_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewNewOpts creates a new instance of NewOpts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewOpts(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewOpts {
	mock := &NewOpts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
