// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_gosesh

import mock "github.com/stretchr/testify/mock"

// OAuth2Credentials is an autogenerated mock type for the OAuth2Credentials type
type OAuth2Credentials struct {
	mock.Mock
}

type OAuth2Credentials_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuth2Credentials) EXPECT() *OAuth2Credentials_Expecter {
	return &OAuth2Credentials_Expecter{mock: &_m.Mock}
}

// ClientID provides a mock function with given fields:
func (_m *OAuth2Credentials) ClientID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OAuth2Credentials_ClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientID'
type OAuth2Credentials_ClientID_Call struct {
	*mock.Call
}

// ClientID is a helper method to define mock.On call
func (_e *OAuth2Credentials_Expecter) ClientID() *OAuth2Credentials_ClientID_Call {
	return &OAuth2Credentials_ClientID_Call{Call: _e.mock.On("ClientID")}
}

func (_c *OAuth2Credentials_ClientID_Call) Run(run func()) *OAuth2Credentials_ClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OAuth2Credentials_ClientID_Call) Return(_a0 string) *OAuth2Credentials_ClientID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OAuth2Credentials_ClientID_Call) RunAndReturn(run func() string) *OAuth2Credentials_ClientID_Call {
	_c.Call.Return(run)
	return _c
}

// ClientSecret provides a mock function with given fields:
func (_m *OAuth2Credentials) ClientSecret() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientSecret")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OAuth2Credentials_ClientSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientSecret'
type OAuth2Credentials_ClientSecret_Call struct {
	*mock.Call
}

// ClientSecret is a helper method to define mock.On call
func (_e *OAuth2Credentials_Expecter) ClientSecret() *OAuth2Credentials_ClientSecret_Call {
	return &OAuth2Credentials_ClientSecret_Call{Call: _e.mock.On("ClientSecret")}
}

func (_c *OAuth2Credentials_ClientSecret_Call) Run(run func()) *OAuth2Credentials_ClientSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OAuth2Credentials_ClientSecret_Call) Return(_a0 string) *OAuth2Credentials_ClientSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OAuth2Credentials_ClientSecret_Call) RunAndReturn(run func() string) *OAuth2Credentials_ClientSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewOAuth2Credentials creates a new instance of OAuth2Credentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuth2Credentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuth2Credentials {
	mock := &OAuth2Credentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
