// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_providers

import (
	providers "github.com/rlebel12/gosesh/providers"
	mock "github.com/stretchr/testify/mock"
)

// discordOpt is an autogenerated mock type for the discordOpt type
type discordOpt struct {
	mock.Mock
}

type discordOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *discordOpt) EXPECT() *discordOpt_Expecter {
	return &discordOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *discordOpt) Execute(_a0 *providers.Discord) {
	_m.Called(_a0)
}

// discordOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type discordOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *providers.Discord
func (_e *discordOpt_Expecter) Execute(_a0 interface{}) *discordOpt_Execute_Call {
	return &discordOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *discordOpt_Execute_Call) Run(run func(_a0 *providers.Discord)) *discordOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*providers.Discord))
	})
	return _c
}

func (_c *discordOpt_Execute_Call) Return() *discordOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *discordOpt_Execute_Call) RunAndReturn(run func(*providers.Discord)) *discordOpt_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newDiscordOpt creates a new instance of discordOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDiscordOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *discordOpt {
	mock := &discordOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
