// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_providers

import (
	providers "github.com/rlebel12/gosesh/providers"
	mock "github.com/stretchr/testify/mock"
)

// DiscordOpt is an autogenerated mock type for the DiscordOpt type
type DiscordOpt struct {
	mock.Mock
}

type DiscordOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscordOpt) EXPECT() *DiscordOpt_Expecter {
	return &DiscordOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *DiscordOpt) Execute(_a0 *providers.Discord) {
	_m.Called(_a0)
}

// DiscordOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DiscordOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *providers.Discord
func (_e *DiscordOpt_Expecter) Execute(_a0 interface{}) *DiscordOpt_Execute_Call {
	return &DiscordOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *DiscordOpt_Execute_Call) Run(run func(_a0 *providers.Discord)) *DiscordOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*providers.Discord))
	})
	return _c
}

func (_c *DiscordOpt_Execute_Call) Return() *DiscordOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *DiscordOpt_Execute_Call) RunAndReturn(run func(*providers.Discord)) *DiscordOpt_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiscordOpt creates a new instance of DiscordOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscordOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscordOpt {
	mock := &DiscordOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
