// Code generated by mockery v2.42.0. DO NOT EDIT.

package mock_providers

import (
	providers "github.com/rlebel12/gosesh/providers"
	mock "github.com/stretchr/testify/mock"
)

// GoogleOpt is an autogenerated mock type for the GoogleOpt type
type GoogleOpt struct {
	mock.Mock
}

type GoogleOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleOpt) EXPECT() *GoogleOpt_Expecter {
	return &GoogleOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *GoogleOpt) Execute(_a0 *providers.Google) {
	_m.Called(_a0)
}

// GoogleOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GoogleOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *providers.Google
func (_e *GoogleOpt_Expecter) Execute(_a0 interface{}) *GoogleOpt_Execute_Call {
	return &GoogleOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *GoogleOpt_Execute_Call) Run(run func(_a0 *providers.Google)) *GoogleOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*providers.Google))
	})
	return _c
}

func (_c *GoogleOpt_Execute_Call) Return() *GoogleOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *GoogleOpt_Execute_Call) RunAndReturn(run func(*providers.Google)) *GoogleOpt_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogleOpt creates a new instance of GoogleOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleOpt {
	mock := &GoogleOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
